<img src="./images/logo-iug@2x.png" alt="IUG" style="width:300px;"/>

# Data Day@IUG 
**Learning Lab #3**: Data Exploration with Python by Dr. N. Tsourakis

[ntsourakis@iun.ch](ntsourakis@iun.ch)

## Introduction to Python

`Python` is a **programming language** that has been under development for over 25 years.

Few key features:
* It is a general purpose programming language.
* Python also provides a powerful toolbox to data scientists.
* It’s open-source, adaptable, and easy to learn. 
* It includes a rich group of libraries and tools.
* It has an enormous community base.
* Major online platforms like Google, Dropbox, Instagram, and Spotify & YouTube — all had worked with this programming language.

### Variables

Understanding the concept of a variable is crucial when getting started with Python and other programming languages. In simplest terms, a `variable` is just a box that you can put stuff in. See of example the boxes below for storing different items.

<img src="./images/storage-boxes.png" alt="Storage Boxes" style="width:600px;"/>

In the same way, we use different types of variables for storing different types of data.

<img src="./images/variables.png" alt="Variables" style="width:600px;"/>

You can use variables to store all kinds of stuff, but for now, we are just going to look at storing numbers and text in variables.

Variables are assigned using a single equal sign =.

The name of the variable is positioned left of the equal sign, while its value is placed on the right-hand side.

Let's create a variable named `my_var` containing a sequence of characters and then print its value.

In [1]:
my_var = "Hello World!"
print(my_var)

Hello World!


We can also create variables of different types. Here is an example for storing integers or floating point numbers.

In [2]:
my_int_var = 3
print(my_int_var)

my_float_var = 10.6
print(my_float_var)

3
10.6


We can alwyas check the type of the variable using the statement below.

In [3]:
type(my_float_var)

float

It's up to us to use meaningful names for the variables, as long as we do not use reserved words of Python.
The following names cannot be used for naming a variable.

In [4]:
import keyword

kw = keyword.kwlist

print(kw)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


<u>Quick exercise</u>: Create your own variables, like the ones you have seen so far.

In [5]:
### Enter your code below this line.

### Arrays

<img src="./images/arrays.png" alt="Arrays Examples" style="width:600px;"/>

In [6]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

In [7]:
x1

array([5, 0, 3, 3, 7, 9])

In [8]:
x1[0]

5

In [9]:
x1[4]

7

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [14]:
x1[0] = 20
x1

array([20,  0,  3,  3,  7,  9])

In [15]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

### String manipulation