<img src="./images/logo-iug@2x.png" alt="IUG" style="width:300px;"/>

# Data Day@IUG 
**Learning Lab #3**: Data Exploration with Python by Dr. N. Tsourakis

[ntsourakis@iun.ch](ntsourakis@iun.ch)

## Introduction to Python

`Python` is a **programming language** that has been under development for over 25 years.

Few key features:
* It is a general purpose programming language.
* Python also provides a powerful toolbox to data scientists.
* It’s open-source, adaptable, and easy to learn. 
* It includes a rich group of libraries and tools.
* It has an enormous community base.
* Major online platforms like Google, Dropbox, Instagram, and Spotify & YouTube — all had worked with this programming language.

### Variables

Understanding the concept of a variable is crucial when getting started with Python and other programming languages. In simplest terms, a `variable` is just a box that you can put stuff in. See of example the boxes below for storing different items.

<img src="./images/storage-boxes.png" alt="Storage Boxes" style="width:600px;"/>

In the same way, we use different types of variables for storing different types of data.

<img src="./images/variables.png" alt="Variables" style="width:600px;"/>

You can use variables to store all kinds of stuff, but for now, we are just going to look at storing numbers and text in variables.

Variables are assigned using a single equal sign =.

The name of the variable is positioned left of the equal sign, while its value is placed on the right-hand side.

Let's create a variable named `my_var` containing a sequence of characters and then print its value.

In [56]:
my_var = "Hello World!"
print(my_var)

Hello World!


We can also create variables of different types. Here is an example for storing integers or floating point numbers.

In [57]:
my_int_var = 3
print(my_int_var)

my_float_var = 10.6
print(my_float_var)

3
10.6


We can alwyas check the type of the variable using the statement below.

In [58]:
type(my_float_var)

float

It's up to us to use meaningful names for the variables, as long as we do not use reserved words of Python.
The following names cannot be used for naming a variable.

In [59]:
import keyword

kw = keyword.kwlist

print(kw)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


<u>Quick exercise</u>: Create your own variables, like the ones you have seen so far.

In [60]:
### Enter your code below this line.

### Arrays

An **array** is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. 

<img src="./images/arrays.png" alt="Arrays Examples" style="width:600px;"/>

``NumPy`` (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It provides **ndarray**, a homogeneous n-dimensional array object, with methods to efficiently operate on it.

Let us create three arrays with numpy.

In [61]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

We can print the dimension, shaoe and size of *x3*.

In [62]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


We can access the data in each cell of the *x1* and *x2* arrays, as shown below.

In [63]:
x1

array([5, 0, 3, 3, 7, 9])

In [64]:
x1[0]

5

In [65]:
x1[4]

7

In [66]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [67]:
x2[0, 0]

3

In [68]:
x2[2, 0]

1

This is how we can change the content of one cell.

In [69]:
x1[0] = 20
x1

array([20,  0,  3,  3,  7,  9])

<u>Quick exercise</u>: Change the contents of *x2* and *x3*.

In [70]:
### Enter your code below this line.

We can even concatanate the contents of two arrays.

In [71]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Concatanating arrays of different dimensions is wrong!

In [72]:
np.concatenate([x1, x2])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### Strings

**Strings** are arrays representing characters. 

Let us create a string and perform some basic manipulations on it.

In [73]:
sentence = "This is a beautiful day!"
print(sentence)

This is a beautiful day!


In [74]:
letter = sentence[0]
print(letter)

T


In [75]:
# Get the length of the string.
len(sentence)

24

<u>Quick exercise</u>: Print the last character of the string.

In [76]:
### Enter your code below this line.

In [77]:
# Find the first occurance of the letter 'a'.
sentence.find('a')


8

In [78]:
# Count the number of spaces.
sentence.count(' ')

4

In [79]:
# Get the first three chars.
sentence[0:3]

'Thi'

<u>Quick exercise</u>: Get the last three characters of the string.

In [80]:
### Enter your code below this line.

In [81]:
# Capitalize the string.
sentence.upper()

'THIS IS A BEAUTIFUL DAY!'

In [82]:
# Replace a substring.
sentence.replace("day", "university")

'This is a beautiful university!'

In [83]:
# Concatenate two strings.
sentence + " Carpe diem!"

'This is a beautiful day! Carpe diem!'